<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

$widget = $this->getWidget();
$postUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/saveWidgetConf', $widget);
$resetUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/resetWidgetConf', $widget);
$refreshUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/refreshWidget', $widget);

?>
<div>
<form action="#" method="get" id="form_widget_config" onsubmit="return false;">
    <?php
    foreach ($this->getWidget()->loadConfig() as $k => $c) {
        if (is_numeric($k)) { // add a custom header
            echo '<h4>'.$c['label'].'</h4>';
            continue;
        }
        ?>
    <fieldset>
        <label class="mh-form-label"><?php echo $c['label']; ?></label>
        <?php switch ($c['type']) {
            case 'text':
            ?>
                <input class="mh-form-input" type="text" name="<?php echo $k; ?>" value="<?php echo $c['value']; ?>" />
                <?php
                break;
            case 'checkbox':
            ?>
                <input class="mh-form-input" type="checkbox" name="<?php echo $k; ?>" <?php echo $c['value'] ? 'checked' : ''; ?>/>
                <?php
                break;
            } ?>
            <legend><?php echo $c['tooltip']; ?></legend>
    </fieldset>
    <?php } ?>
    <input type="submit" value="Save Config" class="mh-form-button"
            onclick="Modalbox.show('<?php echo $postUrl; ?>',
                                   {title: 'Saving Config..',
                                   params: Form.serialize('form_widget_config'),
                                   method: 'post',
                                   afterHide: function() { refreshWidget('<?php echo $this->getTabId().'-'.$widget->getConfigId(); ?>',
                                                                         '<?php echo $refreshUrl; ?>') }
                                  });
                     return false;">
    <input type="button" value="Reset Config" class="mh-form-button"
            onclick="Modalbox.show('<?php echo $resetUrl ?>',
                                   {width: 460,
                                    title: 'Delete Config..',
                                    afterHide: function() { refreshWidget('<?php echo $this->getTabId().'-'.$widget->getConfigId(); ?>',
                                                                          '<?php echo $refreshUrl; ?>') }
                                  });
                     return false;" />
</form>
</div>
