<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

/** @var $this Mage_Core_Block_Template */
?>

<?php // render rows
if ($rows = $this->getRows()) {
    foreach ($rows as $row)
    {
    ?>
<div class="md-item md-item-<?php echo $row['css_id']; ?>">
    <?php if ($row['label'] !== null) { ?>
            <div class="md-icon md-icon-<?php echo $row['css_id'];?>"></div>
            <div class="md-item-title">
                <?php echo $this->__($row['label']) ?>
            </div>
            <div class="md-item-value">
                <?php echo htmlspecialchars($row['value']);?>
            </div>
    <?php } else { // freeform output
            echo $row['value'];
          } ?>
    <?php if (isset($row['chart']) && is_array($row['chart'])) { ?>
    <div class="md-item-<?php echo ((int)$row['chart']['canvas_width'] <= 76) ? 'chart' : 'value'; ?>">
        <?php echo $this->getLayout()->createBlock('magemonitoring/chart')->setData($row['chart'])->toHtml(); ?>
    </div>
    <?php } // endif chart ?>
</div>
<?php
    }
}
// render buttons
if ($buttons = $this->getButtons()) {
    foreach ($buttons as $button) {
        echo $button->toHtml();
     } ?>
<?php } ?>
<div class="clear"></div>
