<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-product-attribute-sets"><?php echo $this->escapeHtml($this->_getHeader()) ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getDeleteButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<table cellspacing="0" width="100%">
    <tr>
        <td width="360" style="border-right:1px solid #ddd; padding:0 23px 23px 0;" class="edit-attribute-set">
            <?php echo $this->getEditWidgetConfigFormHtml() ?>
        </td>
        <td width="320" style="border-right:1px solid #ddd; padding:0 23px 23px 23px;">
            <div class="content-header skip-header">
            <table cellspacing="0">
                    <tbody>
                        <tr>
                            <td><h3><?php echo Mage::helper('catalog')->__('Tab Configuration') ?></h3></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <?php if (!$this->getIsReadOnly()): ?>
                <p><?php echo $this->getAddTabButton() ?>&nbsp;<?php echo $this->getDeleteNodeButton() ?></p>
                <p class="note-block"><?php echo Mage::helper('catalog')->__('Double click on a tab to rename it.') ?></p>
            <?php endif; ?>

            <?php echo $this->getTabTreeHtml() ?>
        </td>
        <td style="padding:0 0 23px 23px;">
            <div class="content-header skip-header">
                <table cellspacing="0">
                    <tbody>
                        <tr>
                            <td><h3><?php echo Mage::helper('catalog')->__('Available Widgets') ?></h3></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="tree-div2" style="height:400px; margin-top:5px;overflow:auto"></div>
            <script type="text/javascript">
            //<![CDATA[
            var allowDragAndDrop = <?php echo ($this->getIsReadOnly() ? 'false' : 'true'); ?>;
            var canEditGroups = <?php echo ($this->getIsReadOnly() ? 'false' : 'true'); ?>;

            var TreePanels = function() {
                // shorthand
                var Tree = Ext.tree;

                return {
                    init : function(){
                        // yui-ext tree

                        var tree = new Ext.tree.TreePanel('tree-div1', {
                            animate:false,
                            loader: false,
                            enableDD: allowDragAndDrop,
                            containerScroll: true,
                            rootVisible: false,
                            copy: true
                        });

                        // set the root node
                        this.root = new Ext.tree.TreeNode({
                            text: 'ROOT',
                            allowDrag:false,
                            allowDrop:true,
                            id:'1'
                        });

                        tree.setRootNode(this.root);
                        buildCategoryTree(this.root, <?php echo $this->getTabTreeJson() ?>);
                        // render the tree
                        tree.render();
                        this.root.expand(false, false);
                        tree.expandAll();

                        this.ge = new Ext.tree.TreeEditor(tree, {
                            allowBlank:false,
                            blankText:'<?php echo Mage::helper('catalog')->__('A name is required') ?>',
                            selectOnFocus:true,
                            cls:'folder'
                        });

                        this.root.addListener('beforeinsert', editSet.leftBeforeInsert);
                        this.root.addListener('beforeappend', editSet.leftBeforeInsert);

                        //this.ge.addListener('beforerender', editSet.editGroup);
                        this.ge.addListener('beforeshow', editSet.editGroup);
                        this.ge.addListener('beforecomplete', editSet.beforeRenameGroup);
                        //this.ge.addListener('startedit', editSet.editGroup);

                        //-------------------------------------------------------------

                        var tree2 = new Ext.tree.TreePanel('tree-div2', {
                            animate:false,
                            loader: false,
                            enableDD: allowDragAndDrop,
                            containerScroll: true,
                            rootVisible: false,
                            lines:false,
                            copy: true
                        });

                        // set the root node
                        this.root2 = new Ext.tree.TreeNode({
                            text: 'ROOT',
                            draggable:false,
                            allowDrop:false,
                            id:'free'
                        });
                        tree2.setRootNode(this.root2);
                        buildCategoryTree(this.root2, <?php echo $this->getWidgetTreeJson() ?>);

                        this.root2.addListener('beforeinsert', editSet.rightBeforeInsert);
                        this.root2.addListener('beforeappend', editSet.rightBeforeAppend);

                        this.root2.addListener('append', editSet.rightAppend);
                        this.root2.addListener('remove', editSet.rightRemove);
                        // render the tree
                        tree2.render();
                        this.root2.expand(false, false);
                        tree2.expandAll();
                    },

                    rebuildTrees : function(){
                        var widgets = new Array();
                        rootNode = TreePanels.root;
                        var gIterator = 0;
                        var wIterator = 0;
                        for( i in rootNode.childNodes ) {
                            if(rootNode.childNodes[i].id) {
                                var group = rootNode.childNodes[i];
                                editSet.req.tabs[gIterator] = new Array(group.id, group.attributes.text.strip(), (gIterator+1));
                                var iterator = 0;
                                for( j in group.childNodes ) {
                                    iterator ++;
                                    if( group.childNodes[j].id ) {
                                        widgets[++wIterator] = new Array(group.childNodes[j].id, group.id, iterator, group.childNodes[j].attributes.impl);
                                    }
                                }
                                iterator = 0;
                            }
                            gIterator ++;
                        }
                        editSet.req.widgets = widgets;

                        editSet.req.not_attributes = new Array();
                        rootNode = TreePanels.root2;

                    }
                };
            }();

            function buildCategoryTree(parent, config){
                if (!config) return null;
                if (parent && config && config.length){
                    for (var i = 0; i < config.length; i++) {
                        var node = new Ext.tree.TreeNode(config[i]);
                        parent.appendChild(node);
                        node.addListener('click', editSet.register);
                        node.addListener('beforemove', editSet.groupBeforeMove);
                        node.addListener('beforeinsert', editSet.groupBeforeInsert);
                        node.addListener('beforeappend', editSet.groupBeforeInsert);
                        if( config[i].children ) {
                            for( j in config[i].children ) {
                                if(config[i].children[j].id) {
                                    newNode = new Ext.tree.TreeNode(config[i].children[j]);
                                    node.appendChild(newNode);
                                }
                            }
                        }
                    }
                }
            }

            var editSet = function() {
                return {
                    register : function(node) {
                        editSet.currentNode = node;
                        editSet.currentLeaf = false;
                    },

                    unregister : function(node) {
                        new Ajax.Updater($('widget_conf_form'), '<?php echo $this->getEditWidgetConfigFormUrl() ?>',
                                { evalScripts: true,
                                  parameters: { tabId: node.parentNode.id,
                                                widgetId: node.id,
                                                widgetImpl: node.attributes.impl
                                                 }
                        });
                        editSet.currentTabId = node.parentNode.id;
                        editSet.currentNode = false;
                        editSet.currentLeaf = node;
                    },

                    deleteSelected : function() {
                        if( TreePanels.root.firstChild == TreePanels.root.lastChild ) {
                            return;
                        }

//                        if( editSet.SystemNodesExists(editSet.currentNode) ) {
//                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('This group contains system attributes. Please move system attributes to another group and try again.')) ?>');
//                            return;
//                        }

                        if (editSet.ConfigurableNodeExists(editSet.currentNode)) {
                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('This group contains attributes, used in configurable products. Please move these attributes to another group and try again.')) ?>');
                            return;
                        }

                        if (editSet.currentLeaf) {
                            TreePanels.root.removeChild(editSet.currentLeaf);
                            editSet.req.removedWidgets.push(new Array(editSet.currentLeaf.parentNode.id, editSet.currentLeaf.id));
                            editSet.currentLeaf = false;
                        }

                        if( editSet.currentNode && editSet.currentNode.attributes.cls == 'folder' ) {
                            TreePanels.root.removeChild(editSet.currentNode);
                            editSet.req.removedTabs.push(editSet.currentNode.id);
                            editSet.currentNode = false;
                        }
                    },

                    SystemNodesExists : function(currentNode) {
                        for( i in currentNode.childNodes ) {
                            if( currentNode.childNodes[i].id ) {
                                child = editSet.currentNode.childNodes[i];
                                if( child.attributes.is_user_defined != 1 ) {
                                    return true;
                                }
                            }
                        }
                    },

                    ConfigurableNodeExists : function(currentNode) {
                        for (var i in currentNode.childNodes ) {
                            if (currentNode.childNodes[i].id) {
                                child = editSet.currentNode.childNodes[i];
                                if (child.attributes.is_configurable) {
                                    return true;
                                }
                            }
                        }
                        return false;
                    },

                    rightAppend : function(node) {
                        return;
                    },

                    addTab : function() {
                        var tab_id = prompt("<?php echo Mage::helper('catalog')->__('Please enter a unique tab id. Example: my_tab') ?>","");
                        tab_id = tab_id.strip();
                        var tab_name = prompt("<?php echo Mage::helper('catalog')->__('Please enter a new tab name. Example: My Tab') ?>","");
                        tab_name = tab_name.strip();
                        if( tab_name == '' || tab_id == '') {
                            this.addTab();
                        } else if( tab_name != false && tab_name != null && tab_name != '' ) {

                            if (!editSet.validateGroupName(tab_name, 0)) {
                                return;
                            }

                            var newNode = new Ext.tree.TreeNode({
                                    text : tab_name.escapeHTML(),
                                    id : tab_id.replace(/-/g,"_").toLowerCase(),
                                    cls : 'folder',
                                    allowDrop : true,
                                    allowDrag : true
                                });
                            TreePanels.root.appendChild(newNode);
                            newNode.addListener('beforemove', editSet.groupBeforeMove);
                            newNode.addListener('beforeinsert', editSet.groupBeforeInsert);
                            newNode.addListener('beforeappend', editSet.groupBeforeInsert);
                            newNode.addListener('click', editSet.register);
                        }
                    },

                    editGroup : function(obj) {
                        if( obj.editNode.attributes.cls != 'folder' || !canEditGroups) {
                             TreePanels.ge.cancelEdit();
                             return false;
                        }
                    },

                    beforeRenameGroup : function(obj, after, before) {
                        return editSet.validateGroupName(after, obj.editNode.id);
                    },

                    validateGroupName : function(name, exceptNodeId) {
                        name = name.strip();
                        if (name === '') {
                            return false;
                        }
                        for (var i=0; i < TreePanels.root.childNodes.length; i++) {
                            if (TreePanels.root.childNodes[i].text.toLowerCase() == name.toLowerCase() && TreePanels.root.childNodes[i].id != exceptNodeId) {
                                errorText = "<?php echo Mage::helper('catalog')->__('Tab with the \"/name/\" name already exists') ?>";
                                alert(errorText.replace("/name/",name));
                                return false;
                            }
                        }
                        return true;
                    },

                    save : function() {
                        $('messages').update();
                        TreePanels.rebuildTrees();
                        if (!editSet.req.form_key) {
                            editSet.req.form_key = FORM_KEY;
                        }
                        var req = {data : Ext.util.JSON.encode(editSet.req)};
                        var con = new Ext.lib.Ajax.request('POST', '<?php echo $this->getSaveUrl() ?>', {success:editSet.success,failure:editSet.failure}, req);
                    },

                    success : function(o) {
                        var response = Ext.util.JSON.decode(o.responseText);
                        if( response.error ) {
                            $('messages').update(response.message);
                        } else if( response.ajaxExpired && response.ajaxRedirect ){
                            setLocation(response.ajaxRedirect);
                        } else if( response.url ){
                            setLocation(response.url);
                        } else if( response.message ) {
                            $('messages').update(response.message);
                        }
                    },

                    failure : function(o) {
                        alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('Unable to complete this request.')) ?>');
                    },

                    groupBeforeMove : function(tree, nodeThis, oldParent, newParent) {
                        if( newParent.attributes.cls == 'folder' && nodeThis.attributes.cls == 'folder' ) {
                            return false;
                        }

                        if( newParent == TreePanels.root && nodeThis.attributes.cls != 'folder' ) {
                            return false;
                        }
                    },

                    rightBeforeAppend : function(tree, nodeThis, node, newParent) {
                        return true;
                        if (node.attributes.is_user_defined == 0) {
                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('You cannot remove system attribute from this set.')) ?>');
                            return false;
                        }
                        else if (node.attributes.is_configurable == 1) {
                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('This attribute is used in configurable products. You cannot remove it from the attribute set.')) ?>');
                            return false;
                        }
                        else {
                            return true;
                        }
                    },

                    rightBeforeInsert : function(tree, nodeThis, node, newParent) {
                        var empty = TreePanels.root2.findChild('id', 'empty');
                        if( empty ) {
                            return false;
                        }
                        return true;
                        if (node.attributes.is_user_defined == 0) {
                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('You cannot remove system attribute from this set.')) ?>');
                            return false;
                        }
                        else if (node.attributes.is_configurable == 1) {
                            alert('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('This attribute is used in configurable products. You cannot remove it from the attribute set.')) ?>');
                            return false;
                        }
                        else {
                            return true;
                        }
                    },

                    groupBeforeInsert : function(tree, nodeThis, node, newParent) {
                        if( node.allowChildren ) {
                            return false;
                        }
                        node.addListener('click', editSet.unregister);
                        if (editSet.currentLeaf && newParent && node.parentNode.id != newParent.parentNode.id) {
                            editSet.req.removedWidgets.push(new Array(editSet.currentLeaf.parentNode.id, editSet.currentLeaf.id));
                        }
                    },

                    rightAppend : function(tree, nodeThis, node) {
                        var empty = TreePanels.root2.findChild('id', 'empty');
                        if( empty && node.id != 'empty' ) {
                            TreePanels.root2.removeChild(empty);
                        }
                    },

                    rightRemove : function(tree, nodeThis, node) {
                        if( nodeThis.firstChild == null && node.id != 'empty' ) {
                            var newNode = new Ext.tree.TreeNode({
                                    text : '<?php echo Mage::helper('catalog')->__('Empty') ?>',
                                    id : 'empty',
                                    cls : 'folder',
                                    is_user_defined : 1,
                                    allowDrop : false,
                                    allowDrag : false
                                });
                            TreePanels.root2.appendChild(newNode);
                        }
                    },

                    leftBeforeInsert : function(tree, nodeThis, node, newParent) {
                        if( node.allowChildren == false ) {
                            return false;
                        }
                    }

                };
            }();

            function saveWidgetConfig(postUrl) {
                var _validator = new Validation('widget_conf_form', {onSubmit:false});
                if( !_validator.validate() ) {
                    return;
                }
                // update node id in tab tree if id changed
                if ($("widget_id").value != $("widget_id_org").value) {
                    $("widget_id").value = $("widget_id").value.replace(/-/g,"_").toLowerCase();
                    $node = TreePanels.root.findChild("id", $("tab_id").value).findChild("id", $("widget_id_org").value);
                    $node.id = $("widget_id").value;
                    $node.attributes.id = $("widget_id").value;
                    editSet.req.removedWidgets.push(new Array($("tab_id").value, $("widget_id_org").value));
                }
                Modalbox.show(postUrl,
                        {title: 'Saving Config..',
                        params: Form.serialize('widget_conf_form'),
                        method: 'post',
                       });
                $("widget_id_org").value = $("widget_id").value;
                return false;
            }

            function initVars() {
                editSet.req = {};
                editSet.req.widgets = false;
                editSet.req.tabs = new Array();
                editSet.req.removedTabs = new Array();
                editSet.req.removedWidgets = new Array();
            }

            initVars();
            Ext.EventManager.onDocumentReady(TreePanels.init, TreePanels, true);
            //]]>
            </script>
        </td>
    </tr>
</table>
