<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

/** @var $this Firegento_MageMonitoring_Block_System_Overview_Read_Tabs_Database */

/** @var $helper Firegento_MageMonitoring_Helper_Database */

$helper = $this->getDatabaseHelper();
$serverInfo = $helper->getMysqlServerInfo();
$serverStatus = $helper->getMysqlServerStatus();
$serverSettingsInformation = $helper->getMysqlServerSettingsInformation();
$innodbBufferInformation = $helper->getMysqlInnodbBufferSizeInformation();

?>

<div class="entry-edit">

    <div class="table healthcheck-box">
        <h2><?php echo $this->__('General Information') ?></h2>

        <div id="shop_configuration">
            <table class="health-table">

                <tbody>
                    <?php foreach ($serverInfo as $config): ?>
                        <tr>
                            <td><?php echo ucfirst($config['label']) ?></td>
                            <td><?php echo $config['value'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="table healthcheck-box">
        <h2><?php echo $this->__($innodbBufferInformation['label']) ?></h2>

        <div id="shop_configuration">
            <table class="health-table">
                <tr>
                    <th><?php echo $this->__('Setting') ?></th>
                    <th><?php echo $this->__('Value') ?></th>
                    <th><?php echo $this->__('Setting') ?></th>
                    <th><?php echo $this->__('Value') ?></th>
                </tr>
                <tbody>
                <tr class="health-<?php echo $innodbBufferInformation['check'] ?>">
                    <?php foreach ($innodbBufferInformation['settings'] as $setting => $value): ?>
                        <td><?php echo $setting ?></td>
                        <td><?php echo $value ?></td>
                    <?php endforeach; ?>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="table healthcheck-box">
        <h2><?php echo $this->__('Settings Information') ?></h2>

        <div id="shop_configuration">
            <table class="health-table">
                <tr>
                    <th><?php echo $this->__('Setting') ?></th>
                    <th><?php echo $this->__('Value') ?></th>
                </tr>
                <tbody>
                <?php foreach ($serverSettingsInformation as $config): ?>
                    <tr class="health-<?php echo $config['label'] ?>">
                        <td><?php echo ucfirst($config['label']) ?></td>
                        <td><?php echo $config['value'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="table healthcheck-box">
        <h2><?php echo $this->__('Status Information') ?></h2>

        <div id="shop_configuration">
            <table class="health-table">
                <tr>
                    <th><?php echo $this->__('Setting') ?></th>
                    <th><?php echo $this->__('Value') ?></th>
                </tr>
                <tbody>
                <?php foreach ($serverStatus as $config): ?>
                    <tr>
                        <td><?php echo ucfirst($config['label']) ?></td>
                        <td><?php echo $config['value'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
