<?php
$widget = $this->getWidget();
$postUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/saveWidgetConf', $widget);
$resetUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/resetWidgetConf', $widget);
$refreshUrl = Mage::helper('magemonitoring')->getWidgetUrl('*/*/refreshWidget', $widget);
?>
<div>
<form action="#" method="get" id="form_widget_config" onsubmit="return false;">
    <?php
    foreach ($this->getWidget()->loadConfig() as $k => $c) {
        if (is_numeric($k)) { // add a custom header
            echo '<h4>'.$c['label'].'</h4>';
            continue;
        }
        ?>
    <fieldset>
        <label class="mh-form-label"><?php echo $c['label']; ?></label>
        <?php switch ($c['type']) {
            case 'text':
            ?>
                <input class="mh-form-input" type="text" name="<?php echo $k; ?>" value="<?php echo $c['value']; ?>" />
                <?php
                break;
            case 'checkbox':
            ?>
                <input class="mh-form-input" type="checkbox" name="<?php echo $k; ?>" <?php echo $c['value'] ? 'checked' : ''; ?>/>
                <?php
                break;
            } ?>
            <legend><?php echo $c['tooltip']; ?></legend>
    </fieldset>
    <?php } ?>
    <input type="submit" value="Save Config" class="mh-form-button"
            onclick="Modalbox.show('<?php echo $postUrl; ?>',
                                   {title: 'Saving Config..',
                                   params: Form.serialize('form_widget_config'),
                                   method: 'post',
                                   afterHide: function() { refreshWidget('<?php echo $this->getTabId().'-'.$widget->getConfigId(); ?>',
                                                                         '<?php echo $refreshUrl; ?>') }
                                  });
                     return false;">
    <input type="button" value="Reset Config" class="mh-form-button"
            onclick="Modalbox.show('<?php echo $resetUrl ?>',
                                   {width: 460,
                                    title: 'Delete Config..',
                                    afterHide: function() { refreshWidget('<?php echo $this->getTabId().'-'.$widget->getConfigId(); ?>',
                                                                          '<?php echo $refreshUrl; ?>') }
                                  });
                     return false;" />
</form>
</div>
