<?php

$checkId = $this->getCheck()->getCheckId();

?>
<div class="<?php echo $this->getCheck()->getContentType() ?> healthcheck-box">
    <h2><?php echo $this->__($this->getCheck()->getTitle()); ?></h2>

    <div id="<?php echo $checkId; ?>"></div>

    <?php  if ($this->getCheck()->getType() == Hackathon_MageMonitoring_Helper_Data::TYPE_ONDEMAND): ?>
        <button onclick="Hackathon_MageMonitoring.showData('<?php echo $checkId; ?>');" class="button execute-button">
            <span>
                <span>
                    <?php echo $this->__('Execute Check') ?>
                </span>
            </span>
        </button>
    <?php else: ?>
        <script>
            jQuery(document).ready(function() {
                Hackathon_MageMonitoring.showData('<?php echo $checkId; ?>');
            });
        </script>

    <?php endif; ?>

</div>