<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

?>
<h4>Watch Dogs with runtime errors:</h4>
<?php foreach ($this->getErrors() as $error) {
          $dog = $error['watchdog'];
?>
<table>
    <thead>
        <tr><th><?php echo $dog->getDogName(); ?></th></tr>
    </thead>
<tbody>
    <tr>
        <td>Class: <?php echo $dog->getDogId()?></td>
    </tr>
    <tr>
        <td>Message: <?php echo $error['exception']->getMessage()?></td>
    </tr>
    <tr>
        <td>Trace: <?php echo $error['exception']->getTraceAsString()?></td>
    </tr>
    </tbody>
</table>
<?php } ?>
