<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>

<?php foreach ($this->getReports() as $report) {
          $dog = $report['watchdog'];
?>
<table>
    <thead>
        <tr><th><?php echo $dog->getDogName()?></th></tr>
    </thead>
    <tbody>
    <?php foreach ($report['output'] as $o) { ?>
        <tr class="<?php echo $o['css_id']; ?>">
            <td><?php echo $o['label']?></td>
            <td><?php echo $o['value']?></td>
        </tr>
    <?php } // end foreach ?>
    </tbody>
</table>
<?php } ?>
