<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageMonitoring
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

/** @var $this Firegento_MageMonitoring_Block_Widget */

?>
<div class="entry-edit">
    <div class="entry-edit-head collapseable md-relative">
        <a title="Toggle Widget.."
            onclick="toggleWithLoad('<?php echo $this->getWidgetId(); ?>',
                                    '<?php echo $this->getRefreshUrl();?>'); return false;"
            href="#" id="<?php echo $this->getWidgetId(); ?>-head"
            class="widget-collapse"><?php echo $this->getName(); ?>
        </a>
        <div class="md-additional-controls">
            <a title="Refresh Widget.." onclick="refreshWidget('<?php echo $this->getWidgetId(); ?>',
                                                               '<?php echo $this->getRefreshUrl() ?>'); return false;"
                                        href="#" class="md-icon-refresh md-icon md-icon-conf"
                                        id="refresh-<?php echo $this->getWidgetId(); ?>"></a>
            <?php if ($this->getConfig()) { ?>
                <a title="Settings.." onclick="openWidgetConf('<?php echo $this->getName(); ?>',
                                                              '<?php echo $this->getConfigUrl() ?>');  return false;"
                                      href="#" class="md-icon-conf md-icon"></a>
            <?php } ?>
        </div>
    </div>
    <fieldset id="<?php echo $this->getWidgetId(); ?>" class="collapseable">
        <div class="monitoring-data-container">
        <?php
                // render widget output
                echo $this->getChildhtml();
        ?>
        </div>
    </fieldset>
    <script type="text/javascript">
        //<![CDATA[
        Fieldset.<?php echo $this->displayCollapsed() ? 'apply' : 'toggle'; ?>Collapse('<?php echo $this->getWidgetId(); ?>');
        $('refresh-<?php echo $this->getWidgetId(); ?>').addClassName('<?php echo $this->displayCollapsed() ? 'control-invis' : '' ?> ');
        //]]>
    </script>
</div>
