<h3 class="monitoring-section-title">Title test</h3>
<h4 class="monitoring-section-title">Sub title test</h4>
<div class="monitoring-data-container">
    <div class="md-item md-item-info">
        <div class="md-icon md-icon-info"></div>
        <div class="md-item-title">Web Server</div>
        <div class="md-item-value">Apache</div>
    </div>
    <div class="md-item md-item-success">
        <div class="md-icon md-icon-succes"></div>
        <div class="md-item-title">Web Server</div>
        <div class="md-item-value">Apache</div>
    </div>
    <div class="md-item md-item-warning">
        <div class="md-icon md-icon-warning"></div>
        <div class="md-item-title">Web Server</div>
        <div class="md-item-value">Apache</div>
    </div>
    <div class="md-item md-item-error">
        <div class="md-icon md-icon-error"></div>
        <div class="md-item-title">Web Server</div>
        <div class="md-item-value">Apache</div>
    </div>
</div>