<div class="entry-edit-head collapseable">
    <a class="open" id="logs_debug-head" href="#" onclick="Fieldset.toggleCollapse('logs_debug'); return false;">
        <?php echo $this->__('Magento Debug Log') ?>
    </a>
</div>
<fieldset id="logs_debug" class="collapseable">
    <div class="monitoring-data-container">
        <div class="md-item md-item-warning">
            <div class="md-item-log"><?php echo nl2br($this->getDebugLog()); ?></div>
        </div>
    </div>
</fieldset>
<script type="text/javascript">
    //<![CDATA[
    Fieldset.applyCollapse('logs_debug');
    //]]>
</script>

<div class="entry-edit-head collapseable">
    <a class="open" id="logs_exception-head" href="#" onclick="Fieldset.toggleCollapse('logs_exception'); return false;">
        <?php echo $this->__('Magento Exception Log') ?>
    </a>
</div>
<fieldset id="logs_exception" class="collapseable">
    <div class="monitoring-data-container">
        <div class="md-item md-item-error">
            <div class="md-item-log"><?php echo nl2br($this->getExceptionLog(60)); ?></div>
        </div>
    </div>
</fieldset>
<script type="text/javascript">
    //<![CDATA[
    Fieldset.toggleCollapse('logs_exception');
    //]]>
</script>
