<?php

/* @var $this Hackathon_MageMonitoring_Block_System_Overview_Read_Tabs_Rewrites */
$rewritesList = $this->getRewritesInfo();

?>

<?php if ($rewritesList === false): ?>
    <?php echo $this->__('This instance does not have any rewrites defined, hurray for the clean implementation!') ?>
<?php else: ?>
    <?php if (!empty($rewritesList['blocks'])): ?>
    <div class="entry-edit-head collapseable">
        <a class="open" id="blocks_rewrites_list-head" href="#" onclick="Fieldset.toggleCollapse('blocks_rewrites_list'); return false;">
            <?php echo $this->__('Blocks Rewrites') ?>
        </a>
    </div>
    <fieldset id="blocks_rewrites_list" class="collapseable">
        <div class="monitoring-data-container">
            <?php foreach ($rewritesList['blocks'] as $node => $rewriteInfo): ?>
            <div class="md-item md-item-info">
                <div class="md-icon md-icon-<?php echo $this->getIconType($rewriteInfo) ?>"></div>
                <div class="md-item-title"><?php echo $node ?></div>
                <div class="md-item-value"><?php echo implode(', ', array_values($rewriteInfo['classes'])) ?></div>
            </div>
            <?php endforeach; ?>
        </div>
    </fieldset>
    <script type="text/javascript">
        //<![CDATA[
        Fieldset.toggleCollapse('blocks_rewrites_list');
        //]]>
    </script>
    <?php endif; ?>
    <?php if (!empty($rewritesList['helpers'])): ?>
        <div class="entry-edit-head collapseable">
            <a class="open" id="helpers_rewrites_list-head" href="#" onclick="Fieldset.toggleCollapse('helpers_rewrites_list'); return false;">
                <?php echo $this->__('Helpers Rewrites') ?>
            </a>
        </div>
        <fieldset id="helpers_rewrites_list" class="collapseable">
            <div class="monitoring-data-container">
                <?php foreach ($rewritesList['helpers'] as $node => $rewriteInfo): ?>
                    <div class="md-item md-item-info">
                        <div class="md-icon md-icon-<?php echo $this->getIconType($rewriteInfo) ?>"></div>
                        <div class="md-item-title"><?php echo $node ?></div>
                        <div class="md-item-value"><?php echo implode(', ', array_values($rewriteInfo['classes'])) ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
        <script type="text/javascript">
        //<![CDATA[
        Fieldset.toggleCollapse('helpers_rewrites_list');
        //]]>
        </script>
    <?php endif; ?>
    <?php if (!empty($rewritesList['models'])): ?>
        <div class="entry-edit-head collapseable">
            <a class="open" id="models_rewrites_list-head" href="#" onclick="Fieldset.toggleCollapse('models_rewrites_list'); return false;">
                <?php echo $this->__('Models Rewrites') ?>
            </a>
        </div>
        <fieldset id="models_rewrites_list" class="collapseable">
            <div class="monitoring-data-container">
                <?php foreach ($rewritesList['models'] as $node => $rewriteInfo): ?>
                    <div class="md-item md-item-info">
                        <div class="md-icon md-icon-<?php echo $this->getIconType($rewriteInfo) ?>"></div>
                        <div class="md-item-title"><?php echo $node ?></div>
                        <div class="md-item-value"><?php echo implode(', ', array_values($rewriteInfo['classes'])) ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
        <script type="text/javascript">
        //<![CDATA[
        Fieldset.toggleCollapse('models_rewrites_list');
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>